MANAGER_PROMPTS = [
    "Assess spillover risks from Israel–Lebanon hostilities on Eastern Med ports.",
    "How do United States–China relations affect semiconductor logistics?",
    "Which tariff changes could disrupt electronics supply chains this quarter?",
    "Summarize cyber incidents targeting logistics/3PL providers recently.",
    "How do GPS spoofing incidents disrupt maritime navigation?",
    "What are the operational implications of Zambia’s national disaster declaration on crop supply, pricing, and import needs?",
    "Which drought-prone regions present the highest near-term yield risk, and what alternative sourcing options exist?",
    "Which horticulture supply chains are most price-sensitive to recent weather shocks in Asia and Africa?",
    "How are farm disaster-aid eligibility criteria changing, and what is the outlook for income caps or coverage limits?",
    "Which supplier regions face the highest risk of yield shortfalls next quarter, and what dual-sourcing steps are recommended?",
    "How are Red Sea security risks reshaping Asia–Europe ocean routing and transit times?",
    "Summarize labor actions and strikes affecting ports, rail, and trucking in North America recently.",
    "Summarize ransomware and OT breaches in maritime terminals and their operational impacts.",
    "Which recent typhoons or cyclones disrupted port calls in East and South Asia, and where are diversions?",
    "Which sanctions designations since 2024 have materially changed shipping patterns for oil and metals?",
    "How is warehouse vacancy and rent trending in key hubs, and what are the implications for 3PLs?",
    "Summarize drought impacts on soybean and corn export programs and vessel lineups.",
    "Which apparel sourcing countries face elevated geopolitical or climate risks this season?"
    "Which Mississippi River constraints are affecting US grain exports and barge rates?",
    "Summarize UK Border Target Operating Model changes and their effect on EU–UK agrifood trade.",
    "How are port automation upgrades changing labor relations and reliability at major gateways?",
    "Which migrant or border policy shifts are affecting cross-border trucking in North America?",
    "Summarize recent LNG liquefaction or regas outages and impacts on European gas import logistics.",
    "Which container equipment imbalances are driving leasing rates and repositioning costs?",
    "Summarize cyber extortion cases targeting freight forwarders and customs brokers recently.",
    "How are fuel price swings influencing bunker surcharges and ocean freight contracts?",
    "Summarize the role of dark fleet tankers in sanctions evasion and trade compliance risks.",
    "Assess cyber extortion risks facing customs brokers and digital clearance platforms.",
    "Assess political risk to supply chains from elections in key sourcing markets this year.",
    "Assess the effect of drone and missile attacks on Red Sea shipping lanes for container reliability.",
    "Which migrant or border tensions in the Americas are slowing cross-border trucking?",
    "Which Middle East flashpoints present the highest disruption risk to oil tanker flows?",
    "How are GPS spoofing attacks disrupting container vessel navigation?",
    "How are dark web leaks of freight data affecting shipment security?",
    "Assess the impact of port worker strikes in Asia on global container flows.",
    "Summarize dockworker contract negotiations in Europe and US East Coast ports.",
    "Assess war-risk implications for Black Sea transit corridors.",
    "Assess copper supply disruptions from power rationing in Zambia and DRC.",
    "Assess sanctions-driven shifts in Russian oil tanker routes.",
    "How are trade wars impacting electronics and component supply chains?",
    "Assess WTO disputes affecting global tariff schedules in 2025.",
    "Summarize trucking corridor blockades in Latin America.",
    "How are interest rate shifts altering inventory holding strategies?",
    "How is automation changing labor relations in ports and warehouses?",
    "Assess risks of tech failures in AI-driven shipping platforms.",
    "How are fuel price hikes reshaping last-mile delivery cost models?",
    "Assess warehouse automation readiness for e-commerce growth in Europe.",
]
